// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("Iulian Margarintescu")]
[assembly: AssemblyCopyrightAttribute("Copyright Iulian Margarintescu © 2015")]
[assembly: AssemblyProductAttribute("Concurrency Utilities")]
[assembly: AssemblyDescriptionAttribute("Utilities for performing efficient concurrent operations")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.1.4")]
[assembly: AssemblyFileVersionAttribute("0.1.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.4";
    }
}
